### ISSUE TITLE
Unable to train without using GPU.

### ISSUE THREAD

**Issue by cardboardcode** [ros-industrial/easy_perception_deployment#12]
Encountered the following terminal error output when attempting to train using only **CPU**.
```bash

Warning: Torch did not find available GPUs on this system.
 If your intention is to cross-compile, this is not an error.
By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
Volta (compute capability 7.0), Turing (compute capability 7.5),
and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
If you wish to cross-compile for a single specific architecture,
export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
  File "setup.py", line 14, in get_cuda_bare_metal_version
    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by cardboardcode** [comment]
The Training component of **EPD** has a GPU dependency and a CPU-variant is yet to be created. However, due to the impractical nature of training a model using CPU (~takes 20 hours to train), this CPU-variant is not currently being worked on.
